import 'dart:convert';
import 'dart:io';

import 'api_testRunner_headless.dart';

void main() async {
  stdin
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen((line) async {
    try {
      final req = jsonDecode(line);
      if (req['jsonrpc'] != '2.0') return;

      final id = req['id'];
      final method = req['method'];

      if (method == 'initialize') {
        _send(id, {
          "protocolVersion": "2024-11-05",
          "capabilities": {"tools": {}},
          "serverInfo": {"name": "apidash_agentic_mcp", "version": "1.0.0"}
        });
      } else if (method == 'tools/list') {
        _send(id, {
          "tools": [
            {
              "name": "execute_agentic_step",
              "description":
                  "Executes a single API step. Pass the exact JSON object generated by your system prompt.",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "step_json": {
                    "type": "string",
                    "description":
                        "The stringified JSON object containing the 'request' field."
                  },
                  "base_url": {
                    "type": "string",
                    "description": "The base URL (e.g., http://127.0.0.1:8000)"
                  }
                },
                "required": ["step_json", "base_url"]
              }
            }
          ]
        });
      } else if (method == 'tools/call') {
        final toolName = req['params']['name'];
        if (toolName == 'execute_agentic_step') {
          try {
            final args = req['params']['arguments'];
            final String stepStr = args['step_json'];

            final String baseUrl = args['base_url']
                .toString()
                .replaceAll('localhost', '127.0.0.1');

            final stepJson = jsonDecode(stepStr);
            final requestData = stepJson['request'];

            final suite = {
              "tests": [
                {
                  "name": stepJson['description'] ?? "Agentic Step",
                  "method": requestData['method'],
                  "path": requestData['path'],
                  "headers": requestData['headers'],
                  "body": requestData['body'],
                  "expected_status": 200
                }
              ]
            };

            final logBuffer = StringBuffer();
            logBuffer.writeln("Starting agentic Engine...");
            logBuffer.writeln("[DEBUG] Base URL resolved to: $baseUrl");

            final runner = ApiTestRunner(
              baseUrl,
              logger: (msg) => logBuffer.writeln(msg),
            );

            await runner.runSuite(suite);
            runner.dispose();

            _send(id, {
              "content": [
                {"type": "text", "text": logBuffer.toString()}
              ]
            });
          } catch (e, stack) {
            _send(id, {
              "content": [
                {"type": "text", "text": "DART ENGINE CRASHED: $e\n$stack"}
              ],
              "isError": true
            });
          }
        }
      }
    } catch (e) {}
  });
}

void _send(dynamic id, Map<String, dynamic> result) {
  if (id == null) return;
  stdout.writeln(jsonEncode({"jsonrpc": "2.0", "id": id, "result": result}));
}
